In [2]:
# Create two matrices using nested lists
matrix1 = [[1, 2, 3],
           [4, 5, 6]]

matrix2 = [[7, 8, 9],
           [10, 11, 12]]

# Initialize a result matrix with the same size (2x3)
result = [[0, 0, 0],
          [0, 0, 0]]

# Perform matrix addition using nested loops
for i in range(len(matrix1)):                         #Loop through rows
  for j in range(len(matrix1[0])):                    #Loop through columns
    result[i][j] = matrix1[i][j] + matrix2[i][j]

# Display the result
print("Matrix 1:")
for row in matrix1:
    print(row)
print("Matrix 2:")
for row in matrix2:
    print(row)

print("Addition of Matrices:")
for row in result:
  print(row)

Matrix 1:
[1, 2, 3]
[4, 5, 6]
Matrix 2:
[7, 8, 9]
[10, 11, 12]
Addition of Matrices:
[8, 10, 12]
[14, 16, 18]


In [3]:
# Create two matrices using nested lists
matrix1 = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]

matrix2 = [[7, 8, 9],
           [10, 11, 12],
           [13, 14, 15]]

# Initialize a result matrix with the same size (2x3)
result = [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]

# Perform matrix addition using nested loops
for i in range(len(matrix1)):                         #Loop through rows
  for j in range(len(matrix1[0])):                    #Loop through columns
    result[i][j] = matrix1[i][j] + matrix2[i][j]

# Display the result
print("Matrix 1:")
for row in matrix1:
    print(row)
print("Matrix 2:")
for row in matrix2:
    print(row)

print("Addition of Matrices:")
for row in result:
  print(row)

Matrix 1:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
Matrix 2:
[7, 8, 9]
[10, 11, 12]
[13, 14, 15]
Addition of Matrices:
[8, 10, 12]
[14, 16, 18]
[20, 22, 24]


In [5]:
import numpy as np

a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
b = np.array([[7, 8, 9], 
              [10, 11, 12],
              [13, 14, 15]])

result = a + b
print(result)

[[ 8 10 12]
 [14 16 18]
 [20 22 24]]
